# Generated by Django 5.1.6 on 2025-02-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('likes_account', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('community_name', models.CharField(max_length=30)),
                ('users_count', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=20)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=20)),
                ('post_description', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
