# Generated by Django 5.1.6 on 2025-03-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(default='Without description', max_length=100),
            preserve_default=False,
        ),
    ]
