# Generated by Django 5.1.6 on 2025-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='commmunity_hero',
            field=models.ImageField(default='None', upload_to='community/communities_hero'),
            preserve_default=False,
        ),
    ]
