# Generated by Django 5.1.6 on 2025-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_community_commmunity_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='commmunity_hero',
            field=models.ImageField(default='None', upload_to='community/communities_hero'),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_grid',
            field=models.ImageField(default='None', upload_to='community/communities_grids/'),
        ),
    ]
