# Generated by Django 5.1.6 on 2025-02-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_post_comments_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='community.comment'),
        ),
    ]
