# Generated by Django 5.1.6 on 2025-03-03 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_community_users_count_community_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='community_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
