# Generated by Django 5.1.6 on 2025-03-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_alter_community_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
    ]
