# Generated by Django 5.1.6 on 2025-03-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_remove_community_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='users_count',
            field=models.IntegerField(default=0),
        ),
    ]
