# Generated by Django 5.1.6 on 2025-03-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_community_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='community_id',
            new_name='community',
        ),
    ]
