# Generated by Django 5.1.6 on 2025-03-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_grid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
