# Generated by Django 5.1.6 on 2025-03-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Videogame',
            fields=[
                ('videogame_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('PC', 'Computer'), ('X', 'Xbox'), ('PS', 'Play station'), ('N', 'Nintendo')], max_length=20)),
                ('classification', models.ManyToManyField(related_name='game_classification', to='polls.classification')),
                ('genre', models.ManyToManyField(related_name='game_genre', to='polls.genre')),
            ],
            options={
                'verbose_name': 'Videogame',
                'verbose_name_plural': 'Videogames',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=15, unique=True)),
                ('stock', models.IntegerField(default=0)),
                ('region', models.CharField(choices=[('WW', 'WorldWide'), ('EU', 'Europe'), ('NA', 'North America'), ('LA', 'LATAM'), ('AS', 'Asia'), ('JP', 'Japan'), ('CN', 'China')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Available'), ('R', 'Redeemed'), ('D', 'Duplicated')], default='A', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Licenses', to='polls.videogame')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
