# Generated by Django 5.1.6 on 2025-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_videogamecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogamecomment',
            name='comment',
            field=models.CharField(blank=True, default='No comments yet', max_length=200),
            preserve_default=False,
        ),
    ]
