# Generated by Django 5.1.6 on 2025-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_videogamecomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='videogame_comments', to='polls.videogamecomment'),
        ),
        migrations.AlterField(
            model_name='videogamecomment',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
