# Generated by Django 5.1.6 on 2025-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_videogame_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
