# Generated by Django 5.1.6 on 2025-02-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('community', '0001_initial'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField()),
                ('communities', models.ManyToManyField(related_name='members', to='community.community')),
                ('groups', models.ManyToManyField(related_name='customuser_groups', to='auth.group')),
                ('licenses', models.ManyToManyField(related_name='user_licenses', to='polls.license')),
                ('preferences', models.ManyToManyField(related_name='preferences', to='polls.genre')),
                ('user_permissions', models.ManyToManyField(related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_product', to='polls.license')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='members.customuser')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='OldPassword',
            fields=[
                ('old_password_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=128)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_passwords', to='members.customuser')),
            ],
            options={
                'verbose_name': 'OldPassword',
                'verbose_name_plural': 'OldPasswords',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to='members.customuser')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.CreateModel(
            name='Item_wishlist',
            fields=[
                ('item_wishlist', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_product', to='polls.videogame')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_items', to='members.wishlist')),
            ],
            options={
                'verbose_name': 'Item_wishlist',
                'verbose_name_plural': 'Item_wishlists',
            },
        ),
    ]
