# Generated by Django 5.1.6 on 2025-02-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('members', '0002_alter_customuser_communities_and_more'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='communities',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='community.community'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='licenses',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_licenses', to='polls.license'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferences',
            field=models.ManyToManyField(blank=True, null=True, related_name='preferences', to='polls.genre'),
        ),
    ]
