# Generated by Django 5.1.6 on 2025-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_created_at'),
        ('members', '0003_alter_customuser_communities_and_more'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='members', to='community.community'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='licenses',
            field=models.ManyToManyField(blank=True, related_name='user_licenses', to='polls.license'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='preferences', to='polls.genre'),
        ),
    ]
