# Generated by Django 5.1.6 on 2025-03-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='communities',
        ),
    ]
